// Code generated by "enumer -type=OpType -output=gen_enum_op.go"; DO NOT EDIT.

package vm

import (
	"fmt"
	"strings"
)

const _OpTypeName = "PUSHPOPSTORECALLLOADADDHALTLABELRETJMPJZJNZNOTORANDEQGTLT"

var _OpTypeIndex = [...]uint8{0, 4, 7, 12, 16, 20, 23, 27, 32, 35, 38, 40, 43, 46, 48, 51, 53, 55, 57}

const _OpTypeLowerName = "pushpopstorecallloadaddhaltlabelretjmpjzjnznotorandeqgtlt"

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpTypeIndex)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpTypeName[_OpTypeIndex[i]:_OpTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OpTypeNoOp() {
	var x [1]struct{}
	_ = x[PUSH-(0)]
	_ = x[POP-(1)]
	_ = x[STORE-(2)]
	_ = x[CALL-(3)]
	_ = x[LOAD-(4)]
	_ = x[ADD-(5)]
	_ = x[HALT-(6)]
	_ = x[LABEL-(7)]
	_ = x[RET-(8)]
	_ = x[JMP-(9)]
	_ = x[JZ-(10)]
	_ = x[JNZ-(11)]
	_ = x[NOT-(12)]
	_ = x[OR-(13)]
	_ = x[AND-(14)]
	_ = x[EQ-(15)]
	_ = x[GT-(16)]
	_ = x[LT-(17)]
}

var _OpTypeValues = []OpType{PUSH, POP, STORE, CALL, LOAD, ADD, HALT, LABEL, RET, JMP, JZ, JNZ, NOT, OR, AND, EQ, GT, LT}

var _OpTypeNameToValueMap = map[string]OpType{
	_OpTypeName[0:4]:        PUSH,
	_OpTypeLowerName[0:4]:   PUSH,
	_OpTypeName[4:7]:        POP,
	_OpTypeLowerName[4:7]:   POP,
	_OpTypeName[7:12]:       STORE,
	_OpTypeLowerName[7:12]:  STORE,
	_OpTypeName[12:16]:      CALL,
	_OpTypeLowerName[12:16]: CALL,
	_OpTypeName[16:20]:      LOAD,
	_OpTypeLowerName[16:20]: LOAD,
	_OpTypeName[20:23]:      ADD,
	_OpTypeLowerName[20:23]: ADD,
	_OpTypeName[23:27]:      HALT,
	_OpTypeLowerName[23:27]: HALT,
	_OpTypeName[27:32]:      LABEL,
	_OpTypeLowerName[27:32]: LABEL,
	_OpTypeName[32:35]:      RET,
	_OpTypeLowerName[32:35]: RET,
	_OpTypeName[35:38]:      JMP,
	_OpTypeLowerName[35:38]: JMP,
	_OpTypeName[38:40]:      JZ,
	_OpTypeLowerName[38:40]: JZ,
	_OpTypeName[40:43]:      JNZ,
	_OpTypeLowerName[40:43]: JNZ,
	_OpTypeName[43:46]:      NOT,
	_OpTypeLowerName[43:46]: NOT,
	_OpTypeName[46:48]:      OR,
	_OpTypeLowerName[46:48]: OR,
	_OpTypeName[48:51]:      AND,
	_OpTypeLowerName[48:51]: AND,
	_OpTypeName[51:53]:      EQ,
	_OpTypeLowerName[51:53]: EQ,
	_OpTypeName[53:55]:      GT,
	_OpTypeLowerName[53:55]: GT,
	_OpTypeName[55:57]:      LT,
	_OpTypeLowerName[55:57]: LT,
}

var _OpTypeNames = []string{
	_OpTypeName[0:4],
	_OpTypeName[4:7],
	_OpTypeName[7:12],
	_OpTypeName[12:16],
	_OpTypeName[16:20],
	_OpTypeName[20:23],
	_OpTypeName[23:27],
	_OpTypeName[27:32],
	_OpTypeName[32:35],
	_OpTypeName[35:38],
	_OpTypeName[38:40],
	_OpTypeName[40:43],
	_OpTypeName[43:46],
	_OpTypeName[46:48],
	_OpTypeName[48:51],
	_OpTypeName[51:53],
	_OpTypeName[53:55],
	_OpTypeName[55:57],
}

// OpTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OpTypeString(s string) (OpType, error) {
	if val, ok := _OpTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OpTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OpType values", s)
}

// OpTypeValues returns all values of the enum
func OpTypeValues() []OpType {
	return _OpTypeValues
}

// OpTypeStrings returns a slice of all String values of the enum
func OpTypeStrings() []string {
	strs := make([]string, len(_OpTypeNames))
	copy(strs, _OpTypeNames)
	return strs
}

// IsAOpType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OpType) IsAOpType() bool {
	for _, v := range _OpTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
