// Code generated by "enumer -type=OpType -output=gen_enum_op.go"; DO NOT EDIT.

package vm

import (
	"fmt"
	"strings"
)

const _OpTypeName = "PUSHPOPSTORECALLLOADADDMULSUBDIVHALTLABELRETJMPJZJNZNOTORANDEQGTLT"

var _OpTypeIndex = [...]uint8{0, 4, 7, 12, 16, 20, 23, 26, 29, 32, 36, 41, 44, 47, 49, 52, 55, 57, 60, 62, 64, 66}

const _OpTypeLowerName = "pushpopstorecallloadaddmulsubdivhaltlabelretjmpjzjnznotorandeqgtlt"

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpTypeIndex)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpTypeName[_OpTypeIndex[i]:_OpTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OpTypeNoOp() {
	var x [1]struct{}
	_ = x[PUSH-(0)]
	_ = x[POP-(1)]
	_ = x[STORE-(2)]
	_ = x[CALL-(3)]
	_ = x[LOAD-(4)]
	_ = x[ADD-(5)]
	_ = x[MUL-(6)]
	_ = x[SUB-(7)]
	_ = x[DIV-(8)]
	_ = x[HALT-(9)]
	_ = x[LABEL-(10)]
	_ = x[RET-(11)]
	_ = x[JMP-(12)]
	_ = x[JZ-(13)]
	_ = x[JNZ-(14)]
	_ = x[NOT-(15)]
	_ = x[OR-(16)]
	_ = x[AND-(17)]
	_ = x[EQ-(18)]
	_ = x[GT-(19)]
	_ = x[LT-(20)]
}

var _OpTypeValues = []OpType{PUSH, POP, STORE, CALL, LOAD, ADD, MUL, SUB, DIV, HALT, LABEL, RET, JMP, JZ, JNZ, NOT, OR, AND, EQ, GT, LT}

var _OpTypeNameToValueMap = map[string]OpType{
	_OpTypeName[0:4]:        PUSH,
	_OpTypeLowerName[0:4]:   PUSH,
	_OpTypeName[4:7]:        POP,
	_OpTypeLowerName[4:7]:   POP,
	_OpTypeName[7:12]:       STORE,
	_OpTypeLowerName[7:12]:  STORE,
	_OpTypeName[12:16]:      CALL,
	_OpTypeLowerName[12:16]: CALL,
	_OpTypeName[16:20]:      LOAD,
	_OpTypeLowerName[16:20]: LOAD,
	_OpTypeName[20:23]:      ADD,
	_OpTypeLowerName[20:23]: ADD,
	_OpTypeName[23:26]:      MUL,
	_OpTypeLowerName[23:26]: MUL,
	_OpTypeName[26:29]:      SUB,
	_OpTypeLowerName[26:29]: SUB,
	_OpTypeName[29:32]:      DIV,
	_OpTypeLowerName[29:32]: DIV,
	_OpTypeName[32:36]:      HALT,
	_OpTypeLowerName[32:36]: HALT,
	_OpTypeName[36:41]:      LABEL,
	_OpTypeLowerName[36:41]: LABEL,
	_OpTypeName[41:44]:      RET,
	_OpTypeLowerName[41:44]: RET,
	_OpTypeName[44:47]:      JMP,
	_OpTypeLowerName[44:47]: JMP,
	_OpTypeName[47:49]:      JZ,
	_OpTypeLowerName[47:49]: JZ,
	_OpTypeName[49:52]:      JNZ,
	_OpTypeLowerName[49:52]: JNZ,
	_OpTypeName[52:55]:      NOT,
	_OpTypeLowerName[52:55]: NOT,
	_OpTypeName[55:57]:      OR,
	_OpTypeLowerName[55:57]: OR,
	_OpTypeName[57:60]:      AND,
	_OpTypeLowerName[57:60]: AND,
	_OpTypeName[60:62]:      EQ,
	_OpTypeLowerName[60:62]: EQ,
	_OpTypeName[62:64]:      GT,
	_OpTypeLowerName[62:64]: GT,
	_OpTypeName[64:66]:      LT,
	_OpTypeLowerName[64:66]: LT,
}

var _OpTypeNames = []string{
	_OpTypeName[0:4],
	_OpTypeName[4:7],
	_OpTypeName[7:12],
	_OpTypeName[12:16],
	_OpTypeName[16:20],
	_OpTypeName[20:23],
	_OpTypeName[23:26],
	_OpTypeName[26:29],
	_OpTypeName[29:32],
	_OpTypeName[32:36],
	_OpTypeName[36:41],
	_OpTypeName[41:44],
	_OpTypeName[44:47],
	_OpTypeName[47:49],
	_OpTypeName[49:52],
	_OpTypeName[52:55],
	_OpTypeName[55:57],
	_OpTypeName[57:60],
	_OpTypeName[60:62],
	_OpTypeName[62:64],
	_OpTypeName[64:66],
}

// OpTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OpTypeString(s string) (OpType, error) {
	if val, ok := _OpTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OpTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OpType values", s)
}

// OpTypeValues returns all values of the enum
func OpTypeValues() []OpType {
	return _OpTypeValues
}

// OpTypeStrings returns a slice of all String values of the enum
func OpTypeStrings() []string {
	strs := make([]string, len(_OpTypeNames))
	copy(strs, _OpTypeNames)
	return strs
}

// IsAOpType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OpType) IsAOpType() bool {
	for _, v := range _OpTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
