// Code generated by "enumer -type=ValueType -output=gen_enum_value.go"; DO NOT EDIT.

package vm

import (
	"fmt"
	"strings"
)

const _ValueTypeName = "VTNilVTStringVTIntVTFloatVTBool"

var _ValueTypeIndex = [...]uint8{0, 5, 13, 18, 25, 31}

const _ValueTypeLowerName = "vtnilvtstringvtintvtfloatvtbool"

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueTypeIndex)-1) {
		return fmt.Sprintf("ValueType(%d)", i)
	}
	return _ValueTypeName[_ValueTypeIndex[i]:_ValueTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ValueTypeNoOp() {
	var x [1]struct{}
	_ = x[VTNil-(0)]
	_ = x[VTString-(1)]
	_ = x[VTInt-(2)]
	_ = x[VTFloat-(3)]
	_ = x[VTBool-(4)]
}

var _ValueTypeValues = []ValueType{VTNil, VTString, VTInt, VTFloat, VTBool}

var _ValueTypeNameToValueMap = map[string]ValueType{
	_ValueTypeName[0:5]:        VTNil,
	_ValueTypeLowerName[0:5]:   VTNil,
	_ValueTypeName[5:13]:       VTString,
	_ValueTypeLowerName[5:13]:  VTString,
	_ValueTypeName[13:18]:      VTInt,
	_ValueTypeLowerName[13:18]: VTInt,
	_ValueTypeName[18:25]:      VTFloat,
	_ValueTypeLowerName[18:25]: VTFloat,
	_ValueTypeName[25:31]:      VTBool,
	_ValueTypeLowerName[25:31]: VTBool,
}

var _ValueTypeNames = []string{
	_ValueTypeName[0:5],
	_ValueTypeName[5:13],
	_ValueTypeName[13:18],
	_ValueTypeName[18:25],
	_ValueTypeName[25:31],
}

// ValueTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ValueTypeString(s string) (ValueType, error) {
	if val, ok := _ValueTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ValueTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ValueType values", s)
}

// ValueTypeValues returns all values of the enum
func ValueTypeValues() []ValueType {
	return _ValueTypeValues
}

// ValueTypeStrings returns a slice of all String values of the enum
func ValueTypeStrings() []string {
	strs := make([]string, len(_ValueTypeNames))
	copy(strs, _ValueTypeNames)
	return strs
}

// IsAValueType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ValueType) IsAValueType() bool {
	for _, v := range _ValueTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
