// Code generated by "enumer -type=TokenType -output=gen_enum_token.go"; DO NOT EDIT.

package parser

import (
	"fmt"
	"strings"
)

const _TokenTypeName = "LCURLYRCURLYLPARENRPARENCOMMAColonEqualEqualEqualColonEqualGreaterGreaterEqualLessLessEqualBangEqualBangSLASHPLUSMINUSSTAROrAndIfElseForATIdentifierLiteralPrintVarNumStringEOF"

var _TokenTypeIndex = [...]uint8{0, 6, 12, 18, 24, 29, 34, 39, 49, 59, 66, 78, 82, 91, 100, 104, 109, 113, 118, 122, 124, 127, 129, 133, 136, 138, 148, 155, 160, 163, 166, 172, 175}

const _TokenTypeLowerName = "lcurlyrcurlylparenrparencommacolonequalequalequalcolonequalgreatergreaterequallesslessequalbangequalbangslashplusminusstarorandifelseforatidentifierliteralprintvarnumstringeof"

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenTypeIndex)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenTypeName[_TokenTypeIndex[i]:_TokenTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenTypeNoOp() {
	var x [1]struct{}
	_ = x[LCURLY-(0)]
	_ = x[RCURLY-(1)]
	_ = x[LPAREN-(2)]
	_ = x[RPAREN-(3)]
	_ = x[COMMA-(4)]
	_ = x[Colon-(5)]
	_ = x[Equal-(6)]
	_ = x[EqualEqual-(7)]
	_ = x[ColonEqual-(8)]
	_ = x[Greater-(9)]
	_ = x[GreaterEqual-(10)]
	_ = x[Less-(11)]
	_ = x[LessEqual-(12)]
	_ = x[BangEqual-(13)]
	_ = x[Bang-(14)]
	_ = x[SLASH-(15)]
	_ = x[PLUS-(16)]
	_ = x[MINUS-(17)]
	_ = x[STAR-(18)]
	_ = x[Or-(19)]
	_ = x[And-(20)]
	_ = x[If-(21)]
	_ = x[Else-(22)]
	_ = x[For-(23)]
	_ = x[AT-(24)]
	_ = x[Identifier-(25)]
	_ = x[Literal-(26)]
	_ = x[Print-(27)]
	_ = x[Var-(28)]
	_ = x[Num-(29)]
	_ = x[String-(30)]
	_ = x[EOF-(31)]
}

var _TokenTypeValues = []TokenType{LCURLY, RCURLY, LPAREN, RPAREN, COMMA, Colon, Equal, EqualEqual, ColonEqual, Greater, GreaterEqual, Less, LessEqual, BangEqual, Bang, SLASH, PLUS, MINUS, STAR, Or, And, If, Else, For, AT, Identifier, Literal, Print, Var, Num, String, EOF}

var _TokenTypeNameToValueMap = map[string]TokenType{
	_TokenTypeName[0:6]:          LCURLY,
	_TokenTypeLowerName[0:6]:     LCURLY,
	_TokenTypeName[6:12]:         RCURLY,
	_TokenTypeLowerName[6:12]:    RCURLY,
	_TokenTypeName[12:18]:        LPAREN,
	_TokenTypeLowerName[12:18]:   LPAREN,
	_TokenTypeName[18:24]:        RPAREN,
	_TokenTypeLowerName[18:24]:   RPAREN,
	_TokenTypeName[24:29]:        COMMA,
	_TokenTypeLowerName[24:29]:   COMMA,
	_TokenTypeName[29:34]:        Colon,
	_TokenTypeLowerName[29:34]:   Colon,
	_TokenTypeName[34:39]:        Equal,
	_TokenTypeLowerName[34:39]:   Equal,
	_TokenTypeName[39:49]:        EqualEqual,
	_TokenTypeLowerName[39:49]:   EqualEqual,
	_TokenTypeName[49:59]:        ColonEqual,
	_TokenTypeLowerName[49:59]:   ColonEqual,
	_TokenTypeName[59:66]:        Greater,
	_TokenTypeLowerName[59:66]:   Greater,
	_TokenTypeName[66:78]:        GreaterEqual,
	_TokenTypeLowerName[66:78]:   GreaterEqual,
	_TokenTypeName[78:82]:        Less,
	_TokenTypeLowerName[78:82]:   Less,
	_TokenTypeName[82:91]:        LessEqual,
	_TokenTypeLowerName[82:91]:   LessEqual,
	_TokenTypeName[91:100]:       BangEqual,
	_TokenTypeLowerName[91:100]:  BangEqual,
	_TokenTypeName[100:104]:      Bang,
	_TokenTypeLowerName[100:104]: Bang,
	_TokenTypeName[104:109]:      SLASH,
	_TokenTypeLowerName[104:109]: SLASH,
	_TokenTypeName[109:113]:      PLUS,
	_TokenTypeLowerName[109:113]: PLUS,
	_TokenTypeName[113:118]:      MINUS,
	_TokenTypeLowerName[113:118]: MINUS,
	_TokenTypeName[118:122]:      STAR,
	_TokenTypeLowerName[118:122]: STAR,
	_TokenTypeName[122:124]:      Or,
	_TokenTypeLowerName[122:124]: Or,
	_TokenTypeName[124:127]:      And,
	_TokenTypeLowerName[124:127]: And,
	_TokenTypeName[127:129]:      If,
	_TokenTypeLowerName[127:129]: If,
	_TokenTypeName[129:133]:      Else,
	_TokenTypeLowerName[129:133]: Else,
	_TokenTypeName[133:136]:      For,
	_TokenTypeLowerName[133:136]: For,
	_TokenTypeName[136:138]:      AT,
	_TokenTypeLowerName[136:138]: AT,
	_TokenTypeName[138:148]:      Identifier,
	_TokenTypeLowerName[138:148]: Identifier,
	_TokenTypeName[148:155]:      Literal,
	_TokenTypeLowerName[148:155]: Literal,
	_TokenTypeName[155:160]:      Print,
	_TokenTypeLowerName[155:160]: Print,
	_TokenTypeName[160:163]:      Var,
	_TokenTypeLowerName[160:163]: Var,
	_TokenTypeName[163:166]:      Num,
	_TokenTypeLowerName[163:166]: Num,
	_TokenTypeName[166:172]:      String,
	_TokenTypeLowerName[166:172]: String,
	_TokenTypeName[172:175]:      EOF,
	_TokenTypeLowerName[172:175]: EOF,
}

var _TokenTypeNames = []string{
	_TokenTypeName[0:6],
	_TokenTypeName[6:12],
	_TokenTypeName[12:18],
	_TokenTypeName[18:24],
	_TokenTypeName[24:29],
	_TokenTypeName[29:34],
	_TokenTypeName[34:39],
	_TokenTypeName[39:49],
	_TokenTypeName[49:59],
	_TokenTypeName[59:66],
	_TokenTypeName[66:78],
	_TokenTypeName[78:82],
	_TokenTypeName[82:91],
	_TokenTypeName[91:100],
	_TokenTypeName[100:104],
	_TokenTypeName[104:109],
	_TokenTypeName[109:113],
	_TokenTypeName[113:118],
	_TokenTypeName[118:122],
	_TokenTypeName[122:124],
	_TokenTypeName[124:127],
	_TokenTypeName[127:129],
	_TokenTypeName[129:133],
	_TokenTypeName[133:136],
	_TokenTypeName[136:138],
	_TokenTypeName[138:148],
	_TokenTypeName[148:155],
	_TokenTypeName[155:160],
	_TokenTypeName[160:163],
	_TokenTypeName[163:166],
	_TokenTypeName[166:172],
	_TokenTypeName[172:175],
}

// TokenTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenTypeString(s string) (TokenType, error) {
	if val, ok := _TokenTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenType values", s)
}

// TokenTypeValues returns all values of the enum
func TokenTypeValues() []TokenType {
	return _TokenTypeValues
}

// TokenTypeStrings returns a slice of all String values of the enum
func TokenTypeStrings() []string {
	strs := make([]string, len(_TokenTypeNames))
	copy(strs, _TokenTypeNames)
	return strs
}

// IsATokenType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenType) IsATokenType() bool {
	for _, v := range _TokenTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
