// Code generated by "enumer -type=TokenType -output=gen_enum_token.go"; DO NOT EDIT.

package parser

import (
	"fmt"
	"strings"
)

const _TokenTypeName = "LCURLYRCURLYLPARENRPARENCOMMACOLONEqualEqualEqualGreaterGreaterEqualLessLessEqualBangEqualBangSLASHPLUSMINUSSTAROrAndIfElseForATIdentifierLiteralEOF"

var _TokenTypeIndex = [...]uint8{0, 6, 12, 18, 24, 29, 34, 39, 49, 56, 68, 72, 81, 90, 94, 99, 103, 108, 112, 114, 117, 119, 123, 126, 128, 138, 145, 148}

const _TokenTypeLowerName = "lcurlyrcurlylparenrparencommacolonequalequalequalgreatergreaterequallesslessequalbangequalbangslashplusminusstarorandifelseforatidentifierliteraleof"

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenTypeIndex)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenTypeName[_TokenTypeIndex[i]:_TokenTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenTypeNoOp() {
	var x [1]struct{}
	_ = x[LCURLY-(0)]
	_ = x[RCURLY-(1)]
	_ = x[LPAREN-(2)]
	_ = x[RPAREN-(3)]
	_ = x[COMMA-(4)]
	_ = x[COLON-(5)]
	_ = x[Equal-(6)]
	_ = x[EqualEqual-(7)]
	_ = x[Greater-(8)]
	_ = x[GreaterEqual-(9)]
	_ = x[Less-(10)]
	_ = x[LessEqual-(11)]
	_ = x[BangEqual-(12)]
	_ = x[Bang-(13)]
	_ = x[SLASH-(14)]
	_ = x[PLUS-(15)]
	_ = x[MINUS-(16)]
	_ = x[STAR-(17)]
	_ = x[Or-(18)]
	_ = x[And-(19)]
	_ = x[If-(20)]
	_ = x[Else-(21)]
	_ = x[For-(22)]
	_ = x[AT-(23)]
	_ = x[Identifier-(24)]
	_ = x[Literal-(25)]
	_ = x[EOF-(26)]
}

var _TokenTypeValues = []TokenType{LCURLY, RCURLY, LPAREN, RPAREN, COMMA, COLON, Equal, EqualEqual, Greater, GreaterEqual, Less, LessEqual, BangEqual, Bang, SLASH, PLUS, MINUS, STAR, Or, And, If, Else, For, AT, Identifier, Literal, EOF}

var _TokenTypeNameToValueMap = map[string]TokenType{
	_TokenTypeName[0:6]:          LCURLY,
	_TokenTypeLowerName[0:6]:     LCURLY,
	_TokenTypeName[6:12]:         RCURLY,
	_TokenTypeLowerName[6:12]:    RCURLY,
	_TokenTypeName[12:18]:        LPAREN,
	_TokenTypeLowerName[12:18]:   LPAREN,
	_TokenTypeName[18:24]:        RPAREN,
	_TokenTypeLowerName[18:24]:   RPAREN,
	_TokenTypeName[24:29]:        COMMA,
	_TokenTypeLowerName[24:29]:   COMMA,
	_TokenTypeName[29:34]:        COLON,
	_TokenTypeLowerName[29:34]:   COLON,
	_TokenTypeName[34:39]:        Equal,
	_TokenTypeLowerName[34:39]:   Equal,
	_TokenTypeName[39:49]:        EqualEqual,
	_TokenTypeLowerName[39:49]:   EqualEqual,
	_TokenTypeName[49:56]:        Greater,
	_TokenTypeLowerName[49:56]:   Greater,
	_TokenTypeName[56:68]:        GreaterEqual,
	_TokenTypeLowerName[56:68]:   GreaterEqual,
	_TokenTypeName[68:72]:        Less,
	_TokenTypeLowerName[68:72]:   Less,
	_TokenTypeName[72:81]:        LessEqual,
	_TokenTypeLowerName[72:81]:   LessEqual,
	_TokenTypeName[81:90]:        BangEqual,
	_TokenTypeLowerName[81:90]:   BangEqual,
	_TokenTypeName[90:94]:        Bang,
	_TokenTypeLowerName[90:94]:   Bang,
	_TokenTypeName[94:99]:        SLASH,
	_TokenTypeLowerName[94:99]:   SLASH,
	_TokenTypeName[99:103]:       PLUS,
	_TokenTypeLowerName[99:103]:  PLUS,
	_TokenTypeName[103:108]:      MINUS,
	_TokenTypeLowerName[103:108]: MINUS,
	_TokenTypeName[108:112]:      STAR,
	_TokenTypeLowerName[108:112]: STAR,
	_TokenTypeName[112:114]:      Or,
	_TokenTypeLowerName[112:114]: Or,
	_TokenTypeName[114:117]:      And,
	_TokenTypeLowerName[114:117]: And,
	_TokenTypeName[117:119]:      If,
	_TokenTypeLowerName[117:119]: If,
	_TokenTypeName[119:123]:      Else,
	_TokenTypeLowerName[119:123]: Else,
	_TokenTypeName[123:126]:      For,
	_TokenTypeLowerName[123:126]: For,
	_TokenTypeName[126:128]:      AT,
	_TokenTypeLowerName[126:128]: AT,
	_TokenTypeName[128:138]:      Identifier,
	_TokenTypeLowerName[128:138]: Identifier,
	_TokenTypeName[138:145]:      Literal,
	_TokenTypeLowerName[138:145]: Literal,
	_TokenTypeName[145:148]:      EOF,
	_TokenTypeLowerName[145:148]: EOF,
}

var _TokenTypeNames = []string{
	_TokenTypeName[0:6],
	_TokenTypeName[6:12],
	_TokenTypeName[12:18],
	_TokenTypeName[18:24],
	_TokenTypeName[24:29],
	_TokenTypeName[29:34],
	_TokenTypeName[34:39],
	_TokenTypeName[39:49],
	_TokenTypeName[49:56],
	_TokenTypeName[56:68],
	_TokenTypeName[68:72],
	_TokenTypeName[72:81],
	_TokenTypeName[81:90],
	_TokenTypeName[90:94],
	_TokenTypeName[94:99],
	_TokenTypeName[99:103],
	_TokenTypeName[103:108],
	_TokenTypeName[108:112],
	_TokenTypeName[112:114],
	_TokenTypeName[114:117],
	_TokenTypeName[117:119],
	_TokenTypeName[119:123],
	_TokenTypeName[123:126],
	_TokenTypeName[126:128],
	_TokenTypeName[128:138],
	_TokenTypeName[138:145],
	_TokenTypeName[145:148],
}

// TokenTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenTypeString(s string) (TokenType, error) {
	if val, ok := _TokenTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenType values", s)
}

// TokenTypeValues returns all values of the enum
func TokenTypeValues() []TokenType {
	return _TokenTypeValues
}

// TokenTypeStrings returns a slice of all String values of the enum
func TokenTypeStrings() []string {
	strs := make([]string, len(_TokenTypeNames))
	copy(strs, _TokenTypeNames)
	return strs
}

// IsATokenType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenType) IsATokenType() bool {
	for _, v := range _TokenTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
